FROM node:24-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./

RUN corepack enable && yarn install

COPY . .
RUN yarn build

FROM node:24-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=3000

COPY package.json ./
COPY --from=builder /app/dist ./dist

RUN corepack enable && yarn install --production

EXPOSE 3000

CMD ["yarn", "start"]
