name: cv-bot-local

services:
  cvbot-server:
    container_name: cv-bot-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
