name: cvbot-prod

services:
  cvbot-server:
    container_name: cvbot-backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - ./backend/.env
    expose:
      - "3000"
    networks:
      - proxy-network
      - cvbot-private-network

  cvbot-www:
    container_name: cvbot-frontend-container
    build:
      context: ./www
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - ./www/.env
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

  cvbot-private-network:
    driver: bridge