name: cvbot-local

services:
  cvbot-server:
    container_name: cvbot-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  cvbot-www:
    container_name: cvbot-frontend-container
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: unless-stopped
    env_file:
      - ./www/.env